services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./server.js:/app/server.js
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    restart: unless-stopped
